function formatResults(analysisResults, energyImpact, badge) {
  const summary = generateSummary(analysisResults, energyImpact);
  const detailedIssues = generateDetailedIssues(analysisResults);
  const recommendations = generateRecommendations(analysisResults);
  
  return `
# 🔋 Energy Efficiency Analysis

${badge}

## 📊 Summary
${summary}

## 🎯 Detected Issues
${detailedIssues}

## 💡 Recommendations
${recommendations}

## 📈 Energy Impact Estimate
- ⚡ **Total Energy Waste**: ${energyImpact.totalWaste} Wh per 1000 executions
- 💚 **Potential Savings**: ${energyImpact.totalSavings} Wh per 1000 executions
- 🌍 **CO₂ Equivalent**: ${energyImpact.co2Equivalent} g per 1000 executions
- 💰 **Estimated Cost Savings**: $${energyImpact.estimatedCost} per 1000 executions

## 🔧 How to Fix
Each issue includes a suggestion for improvement. The energy estimates are based on typical usage patterns and may vary depending on your specific environment and scale.

---

*Report generated by [Energy Savvy Code](https://github.com/energy-savvy-code) action*`;
}

function generateSummary(results, impact) {
  const totalIssues = results.reduce((sum, file) => sum + file.issues.length, 0);
  const filesWithIssues = results.filter(r => r.issues.length > 0).length;
  
  let scoreEmoji = '🟢';
  if (impact.severity === 'high') scoreEmoji = '🔴';
  else if (impact.severity === 'medium') scoreEmoji = '🟡';
  
  return `
${scoreEmoji} **Overall Impact Severity**: ${impact.severity.toUpperCase()}
📁 **Files Analyzed**: ${results.length}
⚠️ **Total Issues Found**: ${totalIssues}
📊 **Files with Issues**: ${filesWithIssues}
⭐ **Average Energy Score**: ${calculateAverageScore(results)}/100
  `;
}

function generateDetailedIssues(results) {
  if (results.length === 0) {
    return "✅ No energy anti-patterns detected! Great job!";
  }

  let output = '';
  
  for (const file of results) {
    if (file.issues.length > 0) {
      output += `\n### 📄 ${file.file}\n\n`;
      
      const severityEmoji = {
        'high': '🔴',
        'medium': '🟡',
        'low': '🟢'
      };
      
      file.issues.forEach(issue => {
        output += `${severityEmoji[issue.severity]} **Line ${issue.line}**: ${issue.message}\n`;
        output += `   > 💡 ${issue.suggestion}\n\n`;
      });
    }
  }
  
  return output;
}

function generateRecommendations(results) {
  const recommendations = [];
  const issueTypes = new Set();
  
  results.forEach(file => {
    file.issues.forEach(issue => {
      issueTypes.add(issue.type);
    });
  });

  const recommendationMap = {
    'inefficient_loop': 'Optimize loops by moving invariant calculations outside',
    'chained_array_methods': 'Combine multiple array iterations into a single reduce()',
    'memory_leak': 'Ensure proper variable scope and cleanup',
    'sparse_array': 'Avoid creating sparse arrays with predefined length',
    'loose_equality': 'Use strict equality (===) for better performance and safety',
    'accidental_global': 'Always declare variables with let/const',
    'console_log': 'Remove console.log statements in production code',
    'default': 'Review code for energy efficiency improvements'
  };

  if (issueTypes.size === 0) {
    return "No specific recommendations - your code looks energy efficient!";
  }

  let output = '';
  issueTypes.forEach(type => {
    output += `- ${recommendationMap[type] || recommendationMap.default}\n`;
  });

  return output;
}

function calculateAverageScore(results) {
  if (results.length === 0) return 100;
  const total = results.reduce((sum, file) => sum + file.score, 0);
  return Math.round(total / results.length);
}

module.exports = { formatResults };